### ISSUE TITLE
Different Cases in SQL than DB

### ISSUE THREAD

**Issue by kferrone** [sdementen/piecash#137] opened 2020-09-30 16:14 UTC
The sql cases which are running are all caps, the db is all lower case.

> SELECT gnclock."Hostname", gnclock."PID"

the actual columns are simply `gnlock.hostname` and `gnlock.pid`

I fear this is not the only place this will happen. 

I'm using postgres btw with GnuCash 4.2

my codes

```python
import piecash
book = piecash.open_book(uri_conn="postgres://postgres:password@localhost/gnucash")
```

**Comment by sdementen** [comment] 2020-10-01 19:35
Would it be a duplicate of #92 ?

**Comment by kferrone** [comment] 2020-10-05 02:26
@sdementen My version of piecash is `1.0.0` and gnucash `4.2.0`. The issue #92 says the problem is solved with version `0.19.0`. This means my version is quite a bit newer than the version which supposedly fixed the issue???

**Comment by sdementen** [comment] 2020-10-05 04:30
I share your bewilderment ;-)
I'll have a look

**Comment by sdementen** [comment] 2020-10-20 04:35
fix merged

**Closed by sdementen** 2020-10-20 04:35 UTC
